# Generated by Django 4.2.26 on 2025-12-01 14:57

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileBlob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='The actual file stored in the filesystem', upload_to=files.models.file_upload_path)),
                ('file_hash', models.CharField(db_index=True, help_text='SHA256 hash of file content for deduplication', max_length=64, unique=True)),
                ('size', models.BigIntegerField(help_text='File size in bytes')),
                ('reference_count', models.IntegerField(default=0, help_text='Number of User Files referencing this blob')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStorageQuota',
            fields=[
                ('user_id', models.CharField(help_text='Unique user identifier', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('total_storage_used', models.BigIntegerField(default=0, help_text='Total bytes used by this user (after deduplication)')),
                ('storage_limit', models.BigIntegerField(default=10485760, help_text='Maximum storage allowed for this user in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this quota record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this quota was last updated')),
            ],
            options={
                'verbose_name': 'User Storage Quota',
                'verbose_name_plural': 'User Storage Quotas',
                'indexes': [models.Index(fields=['user_id'], name='quota_user_idx')],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the file (UUID format)', primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, help_text='User ID who uploaded this file', max_length=255)),
                ('original_filename', models.CharField(help_text='Original filename as provided during upload', max_length=255)),
                ('file_type', models.CharField(help_text='MIME type of the file (e.g., application/pdf)', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the file was uploaded')),
                ('blob', models.ForeignKey(help_text='Reference to the physical file blob', on_delete=django.db.models.deletion.PROTECT, related_name='files', to='files.fileblob')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['-uploaded_at'], name='files_uploaded_idx'), models.Index(fields=['user_id'], name='files_user_idx'), models.Index(fields=['user_id', '-uploaded_at'], name='files_user_date_idx')],
            },
        ),
    ]
