# Generated by Django 4.2.26 on 2025-11-16 04:04

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorageQuota',
            fields=[
                ('user_id', models.CharField(help_text='Unique user identifier', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('total_storage_used', models.BigIntegerField(default=0, help_text='Total bytes used by this user (after deduplication)')),
                ('storage_limit', models.BigIntegerField(default=10485760, help_text='Maximum storage allowed for this user in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this quota record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this quota was last updated')),
            ],
            options={
                'verbose_name': 'User Storage Quota',
                'verbose_name_plural': 'User Storage Quotas',
            },
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AddField(
            model_name='file',
            name='file_hash',
            field=models.CharField(db_index=True, default='0000000000000000000000000000000000000000000000000000000000000000', help_text='SHA256 hash of file content for deduplication', max_length=64),
        ),
        migrations.AddField(
            model_name='file',
            name='is_reference',
            field=models.BooleanField(default=False, help_text='True if this is a reference to another file (duplicate)'),
        ),
        migrations.AddField(
            model_name='file',
            name='original_file',
            field=models.ForeignKey(blank=True, help_text='Reference to original file if this is a duplicate', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='files.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='reference_count',
            field=models.IntegerField(default=1, help_text='Number of times this file is referenced (for deduplication)'),
        ),
        migrations.AddField(
            model_name='file',
            name='user_id',
            field=models.CharField(db_index=True, default='unknown', help_text='User ID who uploaded this file (from UserId header)', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='The actual file stored in the filesystem', upload_to=files.models.file_upload_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(help_text='MIME type of the file (e.g., application/pdf)', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the file (UUID format)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_filename',
            field=models.CharField(help_text='Original filename as provided during upload', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the file was uploaded'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['-uploaded_at'], name='files_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_hash'], name='files_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user_id'], name='files_user_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user_id', '-uploaded_at'], name='files_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='userstoragequota',
            index=models.Index(fields=['user_id'], name='quota_user_idx'),
        ),
    ]
