# Generated by Django 5.2.8 on 2025-11-16 04:25

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_userstoragequota_alter_file_options_file_file_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, help_text='The actual file stored in the filesystem (null for references)', null=True, upload_to=files.models.file_upload_path),
        ),
    ]
