# Generated by Django 5.2.8 on 2025-11-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_hash', 'is_reference'], name='files_hash_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.CheckConstraint(check=models.Q(reference_count__gte=0), name='reference_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.CheckConstraint(check=models.Q(size__gte=0), name='size_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.CheckConstraint(check=models.Q(is_reference=False) | models.Q(original_file__isnull=False), name='reference_has_original'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.CheckConstraint(check=models.Q(is_reference=True) | models.Q(original_file__isnull=True), name='original_no_reference'),
        ),
    ]
