# Generated by Django 5.2.8 on 2025-11-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_add_constraints_and_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(db_index=True, help_text='MIME type of the file (e.g., application/pdf)', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference', False)), fields=('file_hash',), name='unique_original_file_hash'),
        ),
    ]
